### PR TITLE
Improved installation instructions and fixed typos

### LINKED ISSUE #2: command not found: psbt_faker
Trying to get psbt_faker up an running, but facing some issues. I’m on macOS 12.4. After cloning the repo, I do:

```sh
❯ python3 --version
Python 3.9.13

❯ python3 -m pip install --editable .
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Obtaining (...)psbt_faker
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Click in /usr/local/lib/python3.9/site-packages (from psbt-faker==1.3) (8.1.3)
Requirement already satisfied: pycoin==0.80 in /usr/local/lib/python3.9/site-packages (from psbt-faker==1.3) (0.80)
Installing collected packages: psbt-faker
  Attempting uninstall: psbt-faker
    Found existing installation: psbt-faker 1.3
    Uninstalling psbt-faker-1.3:
      Successfully uninstalled psbt-faker-1.3
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Running setup.py develop for psbt-faker
Successfully installed psbt-faker-1.3

❯ rehash
❯ psbt_faker --help
zsh: command not found: psbt_faker

```

### PR DESCRIPTION
**Pull request by schjonhaug**
`python3 -m pip install -U pip setuptools` was missing from the installation. Also fixed various typos.

Fixes #2

### CODE REVIEW

**Comment by doc-hex** [comment]
Your editing tools have changed many reasonable ASCII chars into Unicode characters.
- three dots -> ellipsis
- `'` into some sort of other single-quote looking thing

If you could undo those changes, it's good to go, and I'd like to merge.

**Comment by schjonhaug** [comment]
Sure, I can revert them, but the changes were intentional. The “single-quote looking thing” is actually an apostrophe, and ellipsis looks better than three dots.

Is it a problem using Unicode instead of ASCII in these particular cases? I’m not too familiar with Python coding and its limitations.

**Comment by doc-hex** [comment]
Yeah probably better to revert those changes. They will cause trouble on some systems.

**Comment by schjonhaug** [comment]
OK, done.

**Pull request merged**
